---
apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  labels:
    name: catalog-db
  namespace: default
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: catalog-db