---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog
  labels:
    name: catalog
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: catalog
    spec:
      containers:
      - name: catalog
        image: microshop/catalog:latest
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
          env:
          - name: MONGO_HOST
            value: catalog-db:27017
          - name: JAVA_OPTS
            value: -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
